# Generated by Django 6.0.2 on 2026-04-14 17:17

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='chart_of_account',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'chart_of_account',
            },
        ),
        migrations.CreateModel(
            name='warehouse',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'warehouse',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('account_code', models.ForeignKey(blank=True, db_column='account_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.chart_of_account')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='order_master',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('order_type', models.CharField(max_length=50)),
                ('entry_no', models.CharField(max_length=20, unique=True)),
                ('order_date', models.DateField(default=datetime.date.today, editable=False)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_master',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('category_code', models.ForeignKey(db_column='category_code', on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('issue', models.IntegerField(default=0)),
                ('receive', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today, editable=False)),
                ('order_master_idno', models.ForeignKey(db_column='order_master_idno', on_delete=django.db.models.deletion.CASCADE, to='core.order_master')),
                ('product_code', models.ForeignKey(db_column='product_code', on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('warehouse_code', models.ForeignKey(db_column='warehouse_code', on_delete=django.db.models.deletion.CASCADE, to='core.warehouse')),
            ],
            options={
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='order_detail',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('order_master_idno', models.ForeignKey(db_column='order_master_idno', on_delete=django.db.models.deletion.CASCADE, to='core.order_master')),
                ('product_code', models.ForeignKey(db_column='product_code', on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('warehouse_code', models.ForeignKey(db_column='warehouse_code', on_delete=django.db.models.deletion.CASCADE, to='core.warehouse')),
            ],
            options={
                'db_table': 'order_detail',
            },
        ),
    ]
